name: CI (Pull Request)

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node
        id: linter-checks
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          npm i eslint
          npm run lint